name: chapasdk
description: Chapa flutter library to accept payment via Card, Bank or telebirr etc.
version: 0.0.5
homepage: https://github.com/chapa-et/chapa-flutter

environment:
  sdk: '>=2.19.3 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0
  flutter_inappwebview:
  connectivity_plus:
  fluttertoast:
  mockito:
  uuid:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
